name = "Draugr"
uuid = "a1b2c3d4-e5f6-7890-abcd-ef1234567890"
version = "0.1.0"

[deps]
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
KernelAbstractions = "63c18a36-062a-441e-b654-da1e3ab1ce7c"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[weakdeps]
AMDGPU = "21141c5a-9bdb-4563-92ae-f87d6854732e"
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
JLArrays = "27aeb0d3-9eb9-45fb-866b-73c2ecf80fcb"
Jutul = "2b460a1a-8a2b-45b2-b125-b5c536396eb9"
LinearSolve = "7ed4a6bd-45f5-4d41-b270-4a48e9bafcae"
Metal = "dde4c033-4e86-420c-a63e-0dd931031962"
SparseMatricesCSR = "a0a7dd2c-ebf4-11e9-1f05-cf50bc540ca1"

[extensions]
DraugrAMDGPUExt = "AMDGPU"
DraugrCUDAExt = "CUDA"
DraugrJLArraysExt = "JLArrays"
DraugrJutulExt = "Jutul"
DraugrLinearSolveExt = "LinearSolve"
DraugrMetalExt = "Metal"
DraugrSparseMatricesCSRExt = "SparseMatricesCSR"

[compat]
AMDGPU = "1, 2"
CUDA = "5"
JLArrays = "0.3"
JSON3 = "1.14.3"
Jutul = "0.4.16"
KernelAbstractions = "0.9"
LinearSolve = "3"
Metal = "1"
Printf = "1.10.0"
SparseMatricesCSR = "0.6"
julia = "1.10"

[extras]
JLArrays = "27aeb0d3-9eb9-45fb-866b-73c2ecf80fcb"
Jutul = "2b460a1a-8a2b-45b2-b125-b5c536396eb9"
LinearSolve = "7ed4a6bd-45f5-4d41-b270-4a48e9bafcae"
SparseMatricesCSR = "a0a7dd2c-ebf4-11e9-1f05-cf50bc540ca1"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "JLArrays", "Jutul", "SparseMatricesCSR", "LinearSolve"]
